language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install: "curl https://raw.githubusercontent.com/winardiaris/pabrik-ikon/master/install.sh | bash"
script: pabrik -h
